import * as functions from "firebase-functions";
import OpenAI from "openai";

interface ProblemResult {
  id: number;
  problem: string;
  type: string;
  is_correct: boolean;
  confidence: number;
  notes: string;
}

interface GenerateFeedbackRequest {
  results: ProblemResult[];
  totalProblems: number;
  correctCount: number;
}

interface GenerateFeedbackResponse {
  feedback: string;
  success: boolean;
  error?: string;
}

// Initialize OpenAI client
const getOpenAIClient = () => {
  const apiKey = functions.config().openai?.key;
  if (!apiKey) {
    throw new functions.https.HttpsError(
      "failed-precondition",
      "OpenAI API key not configured"
    );
  }
  return new OpenAI({ apiKey });
};

/**
 * Cloud Function to generate personalized feedback for practice sessions using GPT-4.1 mini
 */
export const generatePracticeFeedback = functions.https.onCall(
  async (
    data: GenerateFeedbackRequest,
    context: functions.https.CallableContext
  ): Promise<GenerateFeedbackResponse> => {
    // Verify authentication
    if (!context.auth) {
      throw new functions.https.HttpsError(
        "unauthenticated",
        "User must be authenticated to generate feedback"
      );
    }

    const { results, totalProblems, correctCount } = data;

    if (!results || !Array.isArray(results)) {
      throw new functions.https.HttpsError(
        "invalid-argument",
        "results must be an array"
      );
    }

    try {
      const openai = getOpenAIClient();

      // Prepare problem summary for the LLM
      const problemSummary = results
        .map((r, idx) => {
          const status = r.is_correct ? "✓ Correct" : "✗ Incorrect";
          const notes = r.notes ? ` (${r.notes})` : "";
          return `${idx + 1}. ${r.problem}\n   ${status}${notes}`;
        })
        .join("\n\n");

      const accuracy = ((correctCount / totalProblems) * 100).toFixed(0);
      const problemType = results[0]?.type === "integral" ? "integrals" : "addition problems";

      const prompt = `You are a friendly, encouraging math tutor providing feedback to a student who just completed a practice session.

**Practice Results:**
- Total Problems: ${totalProblems}
- Correct: ${correctCount}
- Accuracy: ${accuracy}%
- Problem Type: ${problemType}

**Detailed Results:**
${problemSummary}

Generate a brief, personalized feedback message (2-3 paragraphs, max 150 words) that:
1. Starts with an encouraging opening based on their performance
2. Highlights what they did well (specific problems or patterns)
3. Gently points out areas for improvement if accuracy < 80%
4. Ends with motivational advice for their next practice session

Keep the tone friendly, supportive, and age-appropriate. Use simple language. Don't use bullet points, just flowing paragraphs.`;

      const completion = await openai.chat.completions.create({
        model: "gpt-4o-mini", // GPT-4.1 mini
        messages: [
          {
            role: "system",
            content: "You are a supportive, encouraging math tutor who gives constructive feedback.",
          },
          {
            role: "user",
            content: prompt,
          },
        ],
        temperature: 0.7,
        max_tokens: 300,
      });

      const feedback = completion.choices[0]?.message?.content || "";

      if (!feedback) {
        throw new Error("No feedback generated by OpenAI");
      }

      return {
        feedback,
        success: true,
      };
    } catch (error) {
      console.error("Feedback generation error:", error);
      return {
        feedback: "",
        success: false,
        error: error instanceof Error ? error.message : "Unknown error occurred",
      };
    }
  }
);

